### ISSUE TITLE
Initialization with previous trials

### ISSUE THREAD

**Issue by BugsBuggy** [xingchenwan/Casmopolitan#3]
Hello together,
to save computational costs I'm trying to intialize Casmopolitan with previously evaluated random search trials.
However, I am not sure if all previous trials are used correctly in the BO search because I get the following warning:
`The input matches the stored training data. Did you forget to call model.train()`
However, when calling `self.optim.restart()` I assume that the model is trained with the stored data (previous trials). So why does this message appear?

My (working) code to initialize with previous trials is as follows:
```python
self.optim.casmopolitan._X = np.empty((0, self.optim.true_dim))
self.optim.casmopolitan._fX = np.empty((0, self.batch_size))
for idx, x in enumerate(self.previous_trials):
    x = x.reshape((1, len(x)))
    self.optim.observe(x, self.previous_metrics[idx])
self.optim.restart()
# Then run BO loop of Casmopolitan 
```

And I use Cosmopolitan with `n_init = 1` (lowest number possible). It seems to me that Cosmopolitan will always run >= 1 additional random search trial(s) on top. Because of the warning above I am not sure if the initialization is successful and Cosmopolitan is using all my previous trials for the BO search.

Is there a better way to initialize with the previous RS trials so that Casmopolitan will not run additional RS trials on top of my initialized trials?

**Comment by xingchenwan** [comment]
Hi there,
Firstly I think ```The input matches the stored training data. Did you forget to call model.train()``` simply means you are trying to predict on the train data. If that's what you want to do then I don't think you need to worry about it.

By default, ```restart``` will erase the stored X and fX data and initialise the GP with new randomly selected (or based on UCB) configurations, so from your code I think if you want to use your own X and fX data you should not call ```restart``` after observing. 

My suggestion to you would be you could modify the ```restart``` function so that it doesn't erase past data, but allow you to pass a custom pair of X and fX to start the GP. I think you may edit https://github.com/xingchenwan/Casmopolitan/blob/main/bo/optimizer.py Line 79 onward by specifying ```self.casmopolitan._X``` and ```self.casmopolitan._fX``` explicitly instead of filling them with random configs.

Hope that helps,
Xingchen

**Comment by BugsBuggy** [comment]
Thanks for the answer!
That's what I also figured out in the meantime. I omitted restart and initialized `self.casmopolitan._X` and `self.casmopolitan._fX`. Restart is called in each iteration here:
https://github.com/xingchenwan/Casmopolitan/blob/40ab84e4062a5e2dfe2454f89fe0bc9323afcb65/main.py#L101
Therefore it seems that I do not even need to modify `restart`, right?

**Comment by xingchenwan** [comment]
Yes sounds right! I think the easiest way in your case is exactly as you did -- initialize _X and _fX with your own data.

Closing this issue for now. Please feel free re-opening it if you have further questions!.

Best,
Xingchen
