### ISSUE TITLE
Avoid one-hot encoding for binary variables?

### ISSUE THREAD

**Issue by TianningGao** [xingchenwan/Casmopolitan#8]
According to the code in "main.py",  binary variables of a problem should be assigned to categorical variables. 
In "bo/optimizer.py", the binary variables are all one-hot encoded, but usually it is redundant to do so. For example, when optimizing "MaxSAT60", we can simply round the variable to {0,1} with only 60 dimensions, rather than one-hot encode it to 120 dimensions.
Is there a way to avoid one-hot encoding for binary variables in Casmopolitan?

**Comment by xingchenwan** [comment]
Hi Tianning,

Thanks for your interest in our work and codebase. I agree with you that in the binary case, we don't really need explicit one-hot encoding, which leads to redundant representations. However, due to time constraints, I have to focus on bug fixing instead of implementation improvements, and it seems to me that the issue is of the latter category, but please let me know otherwise! Please also feel free to send me a PR if you have a fix.

Thank you once again for your interest!
